[general.ground_truth]
model_name = "gpt-4o-mini"
system_prompt = "Evaluate if the following statement. Only answer with True or False."

[general.data]
scale_factor = 1 # 1 to 5
categories = [
    "Simple Base-Table Predicate",
    "Complex Base-Table Predicate",
    "Simple Join",
    "Complex Join",
] # ["equality", "inequality"]


# Mandatory
[[algorithms]]
name = "Extrapolation Sampling"
version = "1.0.0"
filename = "extrapolated_sampling.py"
class = "ExtrapolatedSampling"

# Optional: Overwriting general ground truth configuration
[algorithms.ground_truth]
model_name = "gpt-4o-mini"
system_prompt = "Evaluate if the following statement. Only answer with True or False."

# Optional: Depends on implementation
[algorithms.algorithm_kwargs]
model_name = "gpt-4o-mini"
system_prompt = "Evaluate if the following statement. Only answer with True or False."
sampling_frac = 0.1


# Mandatory
[[algorithms]]
name = "My Selectivity Estimation Algorithm"
version = "1.0.0"
filename = "my_selectivity_estimation_algorithm.py"
class = "MySelectivityEstimationAlgorithm"

# Optional: Overwriting general ground truth configuration
[algorithms.ground_truth]
model_name = "gpt-3.5-turbo"
# system_prompt = ... # e.g. not used

# Optional: Depends on implementation
[algorithms.algorithm_kwargs]
my_special_algorithm_argument = 42
